version: '3.7'

services:
  postgres:
    image: bitnami/postgresql:latest
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=barber
      - POSTGRES_PASSWORD=barber
      - POSTGRES_DB=barber